"""Paquete de autenticación y autorización (Fase F16)."""

from app.core.auth.passwords import (
    hash_password,
    identify_hash_format,
    needs_rehash,
    password_usable,
    verify_password,
)
from app.core.auth.permissions import (
    AuthorizationError,
    Permiso,
    matriz_permisos,
    puede_ver_seccion,
    permisos_de_rol,
    tiene_permiso,
)
from app.core.auth.roles import (
    ETIQUETAS_ROL,
    ROL_ADMINISTRACION,
    ROL_DIRECCION,
    ROL_RECEPCION,
    ROL_RESTAURANTE,
    ROLES_CANONICOS,
    es_direccion,
    etiqueta_rol,
    parse_rol_persistido,
    rol_canonico,
    roles_asignables,
)
from app.core.auth.session import (
    AUTH_SESSION_KEY,
    MSG_LOGIN_FALLIDO,
    AuthSession,
    ResultadoLogin,
    autenticar_usuario,
    get_auth_session,
    iniciar_terminal_restaurante,
    logout,
    necesita_bootstrap,
    require_permiso,
    save_auth_session,
    session_tiene_permiso,
)
from app.core.auth.usecase_guard import require_usecase, usecase_deny_message

__all__ = [
    "AUTH_SESSION_KEY",
    "AuthorizationError",
    "AuthSession",
    "ETIQUETAS_ROL",
    "MSG_LOGIN_FALLIDO",
    "Permiso",
    "ROL_ADMINISTRACION",
    "ROL_DIRECCION",
    "ROL_RECEPCION",
    "ROL_RESTAURANTE",
    "ROLES_CANONICOS",
    "ResultadoLogin",
    "autenticar_usuario",
    "es_direccion",
    "etiqueta_rol",
    "get_auth_session",
    "hash_password",
    "identify_hash_format",
    "iniciar_terminal_restaurante",
    "logout",
    "matriz_permisos",
    "necesita_bootstrap",
    "needs_rehash",
    "parse_rol_persistido",
    "password_usable",
    "permisos_de_rol",
    "puede_ver_seccion",
    "require_permiso",
    "require_usecase",
    "rol_canonico",
    "roles_asignables",
    "save_auth_session",
    "session_tiene_permiso",
    "tiene_permiso",
    "usecase_deny_message",
    "verify_password",
]
